### ISSUE TITLE
Suggested changes

### ISSUE THREAD

**Issue by luisfelipegarcia** [swindle-resume/swindle-resume#13]
Reword: 
Helped lead the creation and updating of tooling for Premium Support.
to: 
Led project to create and update internal tooling for Premium Support.

- By using "project" it may help your resume stand out a bit more.

Reword: 
Helped prepare support for launch by creating and delivering training. 
to: 
Creating and delivering training material for Premium Support on new services.

- "Helped" is redundant, since you have already used it in the previous description.

Eliminate(suggestion): 
"Educated the Service Team about the customer experiences. and how they can best serve the customers with the product."

- This statement is very similar to the previous one, doesn't seem to add value.

**Comment by JasonSwindle** [comment]
Ok, changes made.
